Repository 2sugarcubes/astrograph, pull requests merged in 2025-02, with the labels that each got.

#2 meta: add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#3 meta: create security.md
  SECURITY.md
Labels: documentation

#6 test(ci): speed up testing by not checking beta branch
  .github/workflows/tests.yml
Labels: enhancement

#17 fix(wasm): reduced star count from 1 mil to 100
  wasm/src/lib.rs
Labels: bug

#18 feat(generator): returned observatories along with body tree
  bin/src/cli.rs
  bin/src/main.rs
  lib/benches/program.rs
  lib/src/body/observatory.rs
  lib/src/generator/artifexian/mod.rs
  lib/src/generator/artifexian/star.rs
  lib/src/generator/mod.rs
  lib/tests/generator.rs
  tools/push-check.sh
Labels: enhancement

#20 Feat/constelations
  assets/solar-system.observatories.json
  assets/solar-system.program.json
  assets/test/constellation/observatories.json
  assets/test/constellation/universe.json
  assets/test/rotation.observatories.json
  lib/benches/program.rs
  lib/src/body/observatory.rs
  lib/src/constellation/mod.rs
  lib/src/constellation/weak.rs
  lib/src/generator/artifexian/star.rs
  lib/src/lib.rs
  lib/src/output/logger/eclipse/mod.rs
  lib/src/output/mod.rs
  lib/src/output/svg.rs
  lib/src/program.rs
  lib/tests/file_output.rs
  wasm/src/output/mod.rs
Labels: enhancement

#23 Test/code cov config
  .github/codecov.yml
Labels: documentation

#15 add human-panic for user-friendly error messages
  bin/Cargo.toml
  bin/src/main.rs
Labels: enhancement

#25 Feat/contributing md
  .github/CONTRIBUTING.md
Labels: documentation

#26 Fix/pretty print errors
  Cargo.lock
  bin/src/err.rs
  bin/src/main.rs
Labels: bug

#30 chore(github): rewrite PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/general.md
Labels: meta

#31 chore(github): documentation for new PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#32 fix(web test): change body_id to bodyId
  web/index.js
Labels: bug

#34 ci/update rust toolchain
  .github/workflows/cli-tests.yml
  .github/workflows/lib-tests.yml
  .github/workflows/wasm-tests.yml
Labels: bug

#33 Fix/remove styling from web output
  lib/src/output/svg.rs
  wasm/src/output/mod.rs
Labels: enhancement

#38 ci: fix formatting for labels
  .github/workflows/todos.yml
Labels: meta

#40 ci: set environment variables for manual runs
  .github/workflows/todos.yml
Labels: meta

#63 ci: create a PR on change
  .github/workflows/todos.yml
Labels: meta

#137 ci: add todo comment label to generated issues
  .github/workflows/todos.yml
Labels: meta

#138 ci: stop auto-deleting branches
  .github/workflows/todos.yml
Labels: meta

#140 fix(bin error): flatten multiple errors
  bin/src/err.rs
  bin/src/main.rs
Labels: bug

#141 docs: improve documentating around long match statement
  bin/src/main.rs
Labels: documentation
